<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://een.com/ver10/batterystatus/wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://een.com/ver10/batterystatus/wsdl" name="BatteryStatusControllerService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://een.com/ver10/batterystatus/wsdl" schemaLocation="batterystatus.xsd"/>
        </xsd:schema>
    </types>
    <message name="GetBatteryStatus">
        <part name="parameters" element="tns:GetBatteryStatus"/>
    </message>
    <message name="GetBatteryStatusResponse">
        <part name="parameters" element="tns:GetBatteryStatusResponse"/>
    </message>
    <portType name="BatteryStatus">
        <operation name="GetBatteryStatus">
            <input wsam:Action="http://een.com/ver10/batterystatus/wsdl/GetBatteryStatus" message="tns:GetBatteryStatus"/>
            <output wsam:Action="http://een.com/ver10/batterystatus/wsdl/BatteryStatus/GetBatteryStatusResponse" message="tns:GetBatteryStatusResponse"/>
        </operation>
    </portType>
    <binding name="BatteryStatusPortBinding" type="tns:BatteryStatus">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="GetBatteryStatus">
            <soap:operation soapAction="http://een.com/ver10/batterystatus/wsdl/GetBatteryStatus"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="BatteryStatusControllerService">
        <port name="BatteryStatusPort" binding="tns:BatteryStatusPortBinding" />
    </service>
</definitions>