<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://een.com/ver10/mcd/wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://een.com/ver10/mcd/wsdl" name="MultiChannelDeviceControllerService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://een.com/ver10/mcd/wsdl"
                        schemaLocation="local/een.com/wsdl/ver10/multichanneldevice/schema/multichanneldevice.xsd"/>
        </xsd:schema>
    </types>
    <message name="GetChannelConfigurations">
        <part name="parameters" element="tns:GetChannelConfigurations"/>
    </message>
    <message name="GetChannelConfigurationsResponse">
        <part name="parameters" element="tns:GetChannelConfigurationsResponse"/>
    </message>
    <portType name="MCDController">
        <operation name="GetChannelConfigurations">
            <input wsam:Action="http://een.com/ver10/mcd/wsdl/GetChannelConfigurations" message="tns:GetChannelConfigurations"/>
            <output wsam:Action="http://een.com/ver10/mcd/wsdl/MCDController/GetChannelConfigurationsResponse" message="tns:GetChannelConfigurationsResponse"/>
        </operation>
    </portType>
    <binding name="MCDControllerPortBinding" type="tns:MCDController">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="GetChannelConfigurations">
            <soap:operation soapAction="http://een.com/ver10/mcd/wsdl/GetChannelConfigurations"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="MultiChannelDeviceControllerService">
        <port name="MCDControllerPort" binding="tns:MCDControllerPortBinding" />
    </service>
</definitions>